export const SUB_TYPES = {
  mcq: [
    { label: "Multiple Choice - Standard", value: "mcq_standard" },
    {
      label: "Multiple Choice - Multiple Response",
      value: "mcq_multi_response",
    },
    { label: "Multiple Choice - Block Layout", value: "mcq_block_layout" },
    { label: "Choice Matrix - Standard", value: "cm_standard" },
    { label: "Choice Matrix - Inline", value: "cm_inline" },
    { label: "Choice Matrix - Labels", value: "cm_labels" },
  ],
  fitb: [
    { label: "Cloze with Drag & Drop", value: "cloze_drag_drop" },
    { label: "Cloze with Drop Down", value: "cloze_drop_down" },
    { label: "Cloze with Text", value: "cloze_text" },
    { label: "Label Image with Drag & Drop", value: "image_drag_drop" },
    { label: "Label Image with Drop Down", value: "image_drop_down" },
    { label: "Label Image with Text", value: "image_text" },
  ],
  cl_mt_ord: [
    { label: "Classification", value: "" },
    { label: "Match List", value: "" },
    { label: "Order List", value: "" },
    { label: "Sort List", value: "" },
  ],
  Wr_Re_Ess: [
    { label: "Essay with Rich Text", value: "" },
    { label: "Sort Text", value: "" },
  ],
  high_draw: [
    { label: "Drawing", value: "" },
    { label: "Shading", value: "" },
    { label: "Token Highlight", value: "" },
    { label: "Hotspot", value: "" },
  ],
  math: [
    { label: "Math Fromula", value: "" },
    { label: "Math with Fractions", value: "" },
    { label: "Math - Fill in the Blanks", value: "" },
    { label: "Math with Text", value: "" },
    { label: "Math with matrices", value: "" },
    { label: "Math with units", value: "" },
    { label: "Math essay with rich text", value: "" },
    { label: "Cloze math", value: "" },
    { label: "Cloze math with image", value: "" },
    { label: "Math Question Generator", value: "" },
  ],
  graphing: [
    { label: "Graphing", value: "" },
    { label: "Graphing in the first quardent", value: "" },
    { label: "Number line with drag drop", value: "" },
    { label: "Number line with plot", value: "" },
  ],
  charts: [
    { label: "Bar chart", value: "" },
    { label: "Line chart", value: "" },
    { label: "Histogram", value: "" },
    { label: "Dot plot", value: "" },
    { label: "Line plot", value: "" },
  ],
  chemistry: [
    { label: "Chemistry formula", value: "" },
    { label: "Cloze chemistry", value: "" },
    { label: "Chemistry essay with rich text", value: "" },
    { label: "Cloze chemistry with image", value: "" },
  ],
  desmoz: [{ label: "", value: "" }],
  other: [
    { label: "File upload", value: "" },
    { label: "Image annotation upload", value: "" },
    { label: "Rating", value: "" },
    { label: "Gridded", value: "" },
  ],
};
